package com.acom.entities.model;

import java.sql.Timestamp;

public class AdminModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_module.id
     *
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_module.name
     *
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_module.create_time
     *
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_module.desc
     *
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_module.id
     *
     * @return the value of admin_module.id
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_module.id
     *
     * @param id the value for admin_module.id
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_module.name
     *
     * @return the value of admin_module.name
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_module.name
     *
     * @param name the value for admin_module.name
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_module.create_time
     *
     * @return the value of admin_module.create_time
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_module.create_time
     *
     * @param createTime the value for admin_module.create_time
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_module.desc
     *
     * @return the value of admin_module.desc
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_module.desc
     *
     * @param desc the value for admin_module.desc
     * @mbg.generated Tue Jun 06 17:44:44 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}