package com.acom.entities.model;

import java.sql.Timestamp;

public class AdminModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_module.id
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_module.name
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_module.create_time
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_module.remarks
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_module.id
     *
     * @return the value of admin_module.id
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_module.id
     *
     * @param id the value for admin_module.id
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_module.name
     *
     * @return the value of admin_module.name
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_module.name
     *
     * @param name the value for admin_module.name
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_module.create_time
     *
     * @return the value of admin_module.create_time
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_module.create_time
     *
     * @param createTime the value for admin_module.create_time
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_module.remarks
     *
     * @return the value of admin_module.remarks
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_module.remarks
     *
     * @param remarks the value for admin_module.remarks
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}