package com.acom.entities.model;

import java.sql.Timestamp;

public class BsCacheTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_cache_table.id
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_cache_table.name
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_cache_table.class_path
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private String classPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_cache_table.status
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_cache_table.create_time
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_cache_table.remarks
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_cache_table.id
     *
     * @return the value of bs_cache_table.id
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_cache_table.id
     *
     * @param id the value for bs_cache_table.id
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_cache_table.name
     *
     * @return the value of bs_cache_table.name
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_cache_table.name
     *
     * @param name the value for bs_cache_table.name
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_cache_table.class_path
     *
     * @return the value of bs_cache_table.class_path
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public String getClassPath() {
        return classPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_cache_table.class_path
     *
     * @param classPath the value for bs_cache_table.class_path
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setClassPath(String classPath) {
        this.classPath = classPath == null ? null : classPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_cache_table.status
     *
     * @return the value of bs_cache_table.status
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_cache_table.status
     *
     * @param status the value for bs_cache_table.status
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_cache_table.create_time
     *
     * @return the value of bs_cache_table.create_time
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_cache_table.create_time
     *
     * @param createTime the value for bs_cache_table.create_time
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_cache_table.remarks
     *
     * @return the value of bs_cache_table.remarks
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_cache_table.remarks
     *
     * @param remarks the value for bs_cache_table.remarks
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}