package com.acom.entities.mapper;

import com.acom.entities.model.AdminModule;
import com.acom.entities.model.AdminModuleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdminModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    long countByExample(AdminModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int deleteByExample(AdminModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int insert(AdminModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int insertSelective(AdminModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    List<AdminModule> selectByExample(AdminModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    AdminModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") AdminModule record, @Param("example") AdminModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByExample(@Param("record") AdminModule record, @Param("example") AdminModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByPrimaryKeySelective(AdminModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_module
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByPrimaryKey(AdminModule record);
}