package com.acom.entities.mapper;

import com.acom.entities.model.AdModPriRel;
import com.acom.entities.model.AdModPriRelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdModPriRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    long countByExample(AdModPriRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int deleteByExample(AdModPriRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int insert(AdModPriRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int insertSelective(AdModPriRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    List<AdModPriRel> selectByExample(AdModPriRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    AdModPriRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") AdModPriRel record, @Param("example") AdModPriRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByExample(@Param("record") AdModPriRel record, @Param("example") AdModPriRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByPrimaryKeySelective(AdModPriRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_mod_pri_rel
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByPrimaryKey(AdModPriRel record);
}