package com.acom.entities.mapper;

import com.acom.entities.model.BsCacheTable;
import com.acom.entities.model.BsCacheTableExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BsCacheTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    long countByExample(BsCacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int deleteByExample(BsCacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int insert(BsCacheTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int insertSelective(BsCacheTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    List<BsCacheTable> selectByExample(BsCacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    BsCacheTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") BsCacheTable record, @Param("example") BsCacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByExample(@Param("record") BsCacheTable record, @Param("example") BsCacheTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByPrimaryKeySelective(BsCacheTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_cache_table
     *
     * @mbg.generated Wed Jun 07 16:25:07 CST 2017
     */
    int updateByPrimaryKey(BsCacheTable record);
}